#include "cloth/lexer/token.h"

namespace cloth {

std::string_view token_kind_name(TokenKind kind) noexcept {
  switch (kind) {
    case TokenKind::kEof:
      return "eof";
    case TokenKind::kIdentifier:
      return "identifier";
    case TokenKind::kIntegerLiteral:
      return "integer_literal";
    case TokenKind::kFloatLiteral:
      return "float_literal";
    case TokenKind::kStringLiteral:
      return "string_literal";
    case TokenKind::kCharacterLiteral:
      return "char_literal";
    case TokenKind::kLeftParen:
      return "left_paren";
    case TokenKind::kRightParen:
      return "right_paren";
    case TokenKind::kLeftBrace:
      return "left_brace";
    case TokenKind::kRightBrace:
      return "right_brace";
    case TokenKind::kLeftBracket:
      return "left_bracket";
    case TokenKind::kRightBracket:
      return "right_bracket";
    case TokenKind::kComma:
      return "comma";
    case TokenKind::kSemicolon:
      return "semicolon";
    case TokenKind::kColon:
      return "colon";
    case TokenKind::kColonColon:
      return "colon_colon";
    case TokenKind::kDot:
      return "dot";
    case TokenKind::kQuestion:
      return "question";
    case TokenKind::kQuestionDot:
      return "question_dot";
    case TokenKind::kQuestionQuestion:
      return "question_question";
    case TokenKind::kPlus:
      return "plus";
    case TokenKind::kMinus:
      return "minus";
    case TokenKind::kStar:
      return "star";
    case TokenKind::kSlash:
      return "slash";
    case TokenKind::kPercent:
      return "percent";
    case TokenKind::kEqual:
      return "equal";
    case TokenKind::kEqualEqual:
      return "equal_equal";
    case TokenKind::kBangEqual:
      return "bang_equal";
    case TokenKind::kLess:
      return "less";
    case TokenKind::kLessEqual:
      return "less_equal";
    case TokenKind::kGreater:
      return "greater";
    case TokenKind::kGreaterEqual:
      return "greater_equal";
    case TokenKind::kAmpersandAmpersand:
      return "ampersand_ampersand";
    case TokenKind::kPipePipe:
      return "pipe_pipe";
    case TokenKind::kBang:
      return "bang";
    case TokenKind::kAmpersand:
      return "ampersand";
    case TokenKind::kPipe:
      return "pipe";
    case TokenKind::kCaret:
      return "caret";
    case TokenKind::kTilde:
      return "tilde";
    case TokenKind::kPlusPlus:
      return "plus_plus";
    case TokenKind::kMinusMinus:
      return "minus_minus";
    case TokenKind::kPlusEqual:
      return "plus_equal";
    case TokenKind::kMinusEqual:
      return "minus_equal";
    case TokenKind::kStarEqual:
      return "star_equal";
    case TokenKind::kSlashEqual:
      return "slash_equal";
    case TokenKind::kPercentEqual:
      return "percent_equal";
    case TokenKind::kShiftLeft:
      return "shift_left";
    case TokenKind::kShiftRight:
      return "shift_right";
    case TokenKind::kShiftLeftEqual:
      return "shift_left_equal";
    case TokenKind::kShiftRightEqual:
      return "shift_right_equal";
    case TokenKind::kAmpersandEqual:
      return "ampersand_equal";
    case TokenKind::kPipeEqual:
      return "pipe_equal";
    case TokenKind::kCaretEqual:
      return "caret_equal";
    case TokenKind::kKwFunc:
      return "func";
    case TokenKind::kKwInit:
      return "init";
    case TokenKind::kKwReturn:
      return "return";
    case TokenKind::kKwIf:
      return "if";
    case TokenKind::kKwElse:
      return "else";
    case TokenKind::kKwWhile:
      return "while";
    case TokenKind::kKwFor:
      return "for";
    case TokenKind::kKwIn:
      return "in";
    case TokenKind::kKwBreak:
      return "break";
    case TokenKind::kKwContinue:
      return "continue";
    case TokenKind::kKwStruct:
      return "struct";
    case TokenKind::kKwClass:
      return "class";
    case TokenKind::kKwInterface:
      return "interface";
    case TokenKind::kKwAbstract:
      return "abstract";
    case TokenKind::kKwSealed:
      return "sealed";
    case TokenKind::kKwEnum:
      return "enum";
    case TokenKind::kKwTrait:
      return "trait";
    case TokenKind::kKwLet:
      return "let";
    case TokenKind::kKwVar:
      return "var";
    case TokenKind::kKwConst:
      return "const";
    case TokenKind::kKwFinal:
      return "final";
    case TokenKind::kKwStatic:
      return "static";
    case TokenKind::kKwOverride:
      return "override";
    case TokenKind::kKwSuper:
      return "super";
    case TokenKind::kKwTrue:
      return "true";
    case TokenKind::kKwFalse:
      return "false";
    case TokenKind::kKwNull:
      return "null";
    case TokenKind::kKwExtern:
      return "extern";
    case TokenKind::kKwUnsafe:
      return "unsafe";
    case TokenKind::kKwImport:
      return "import";
    case TokenKind::kKwIs:
      return "is";
    case TokenKind::kKwAs:
      return "as";
    case TokenKind::kKwMatch:
      return "match";
    case TokenKind::kKwInt:
      return "int";
    case TokenKind::kKwInt8:
      return "int8";
    case TokenKind::kKwInt16:
      return "int16";
    case TokenKind::kKwInt32:
      return "int32";
    case TokenKind::kKwInt64:
      return "int64";
    case TokenKind::kKwUint:
      return "uint";
    case TokenKind::kKwUint8:
      return "uint8";
    case TokenKind::kKwUint16:
      return "uint16";
    case TokenKind::kKwUint32:
      return "uint32";
    case TokenKind::kKwUint64:
      return "uint64";
    case TokenKind::kKwFloat:
      return "float";
    case TokenKind::kKwFloat32:
      return "float32";
    case TokenKind::kKwFloat64:
      return "float64";
    case TokenKind::kKwBool:
      return "bool";
    case TokenKind::kKwChar:
      return "char";
    case TokenKind::kKwByte:
      return "byte";
    case TokenKind::kKwVoid:
      return "void";
    case TokenKind::kKwObject:
      return "object";
  }
  return "unknown";
}

}  // namespace cloth
